name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '!api/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build project
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.API_URL }}

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          vercel-args: '--prod'

# API Deployment Workflow
# .github/workflows/api-deploy.yml

name: Deploy API

on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: api/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      # Choose one of these deployment options based on your preference:

      # Option 1: Deploy to Heroku
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "api"

      # Option 2: Deploy to Railway
      # - name: Deploy to Railway
      #   uses: railwayapp/railway-github-action@v1.0.0
      #   with:
      #     railway_token: ${{ secrets.RAILWAY_TOKEN }}
      #     working-directory: ./api

      # Option 3: Deploy to Render
      # - name: Deploy to Render
      #   env:
      #     deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      #   run: |
      #     curl "$deploy_url"

      - name: Health check
        run: |
          sleep 30
          curl -f https://${{ secrets.API_HEALTH_CHECK_URL }} || exit 1